#!/opt/bin/bash

########################################
#### Global
## Binaries
binCurl="curl --retry 3 --silent --insecure --location --show-error"

## Firmware
gsFirmwareVersion="$(nvram get os_version | sed 's/ -/-/g;' | awk '{ print $1 }')"
gsFirmwareYear="v$(echo "${gsFirmwareVersion}" | cut -d '.' -f 1)"

# Kernel Modules
gsDirArmExtras="/opt/MyTomato/root/SCRIPTs/inc/ARM-Extras"
gsUrlArmExtras="https://exotic.se/freshtomato-arm/${gsFirmwareYear}/${gsFirmwareVersion}/arm-extras.tar.gz"

## Locales
gsLocales="en_US"
gsTimezone="Europe/Paris"

########################################
## Files & directories
[ "$0" != "-bash" ] && gsScriptName="$(basename "$0")" || gsScriptName="vars"
# OpenVPN
gsDirOpenVpn="/opt/MyTomato/root/OpenVPN"
# Scripts
gsDirScripts="/opt/MyTomato/root/SCRIPTs"
# Backup
gsDirBackups="/opt/MyTomato/root/BACKUPs"
# Logs (internal use)
gsDirLogs="/opt/var/log"
# Templates
gsDirTemplates="/opt/MyTomato/root/TEMPLATEs"
gsDirOverLoad="/opt/MyTomato/root/ConfigOverload"

########################################
#### USB Disk
gsUsbFileSystem="ext4"
gsUsbOptUuid=""

########################################
#### Logging
gdDateTime="$(date +%Y%m%d_%H%M)"
gsOpkgPackagesList="$([ -d "${gsDirLogs}" ] && /opt/bin/find "${gsDirLogs}/" -type f -name "opkg*" | tail -n 1)"

########################################
#### Services
# P2P Artisan
# https://www.linksysinfo.org/index.php?threads/p2partisan-v5-14-v6-08-mass-ip-blocking-peerblock-peerguardian-for-tomato.69128/
# - Line 7 in p2partisan.sh should be automatically adjusted to your custom path but double check for your peace of mind
# - You might want to have a look at the other parameters set at the beginning of the file just to make sure you're happy with them
# - Edit the whiteports_tcp & whiteports_udp if needed
# - Edit the greyports_tcp & greyports_udp if needed
# - Edit the blacklists file if needed
# - Edit the blacklist-custom if needed
# - Edit the whitelist file if needed
gbP2Partisan_Enable=1                # Off = 0 / On = 1

# DNScrypt-proxy
gbDNScrypt_Enable=1                  # Off = 0 / On = 1
gsWan1_DNS="9.9.9.9 149.112.112.112" # Quad 9 DNS; Add 1 or 2 IP address comma seperated.

# Upgrade MyTomato from GitHub repository
gbRepoUpgrade_Enable=1 # Off = 0 / On = 1

#### Export
export binCurl gsDirArmExtras gsUrlArmExtras gsLocales gsTimezone
export gsScriptName gsDirRoot gsDirScripts gsDirOpenVpn gsDirBackups gsDirLogs gsDirTemplates gsDirOverLoad
export gsUsbFileSystem gsUsbOptUuid gsWan1_DNS
export gdDateTime gsOpkgPackagesList
export gbP2Partisan_Enable gbDNScrypt_Enable gbRepoUpgrade_Enable gbSyslog_Enable
